name = "FinTilsBase"
uuid = "20b8b8ae-5651-4d78-a8e3-e177aef551c4"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
FixedPointDecimals = "0.6.3"
Printf = "1.11.0"
julia = "1.6.7"
