name = "FinTilsBase"
uuid = "20b8b8ae-5651-4d78-a8e3-e177aef551c4"
authors = ["C. Naaktgeboren <NaaktgeborenC.PhD@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Reexport = "1.2.2"
julia = "1.6.7"
